### ISSUE TITLE
(machine) How to go about having two gagent subords related to the same principal

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-k8s-operator#144]
### Enhancement Proposal

Iiuc, the second charm would attempt to install a snap that is already installed, resulting in
```
snap "grafana-agent" is already installed, see 'snap help refresh'
```
which is, btw, 0 return code (i.e. success).

Specifically, it seems like this cannot not give us redundancy, and may create an unintended race. Not sure.

Similarly, what if the principal already happens to have the grafana-agent snap installed?

**Comment by rbarry82** [comment]
Yes, but that's what we want, since the subordinate is "really" running on the principal machine. We could set a limit so they don't walk over each other's configs, though, but this is probably a "don't do that" item which almost nobody will try in real life.

The snap library itself [is idempotent](https://github.com/canonical/operator-libs-linux/blob/main/lib/charms/operator_libs_linux/v1/snap.py#L495), though, and if it's already installed, the worst that happens is that it tries to refresh it when we try [to ensure it's the latest version](https://github.com/canonical/grafana-agent-k8s-operator/blob/884b687702be5c147fe2a081603ec819f1fe69ce/src/machine_charm.py#L165). If it's already on the principal, this is a noop.

That said, the assumption that an operator will manually install the snap on some other charm is pretty antithetical to normal cloud operations, and the same "what if an admin `juju ssh`-es into a machine and initializes postgres/kafka/changes the PAM configuration/etc" are potential risks/"don't do that" in all charms which are not meaningful/supportable scenarios.

**Comment by rbarry82** [comment]
[This PR](https://github.com/canonical/operator-libs-linux/pull/83) will permanently resolve this.

**Comment by sed-i** [comment]
Afaict, that PR does not address the race in writing config files.
But I'm fine with placing it in the "don't do that" bin.

**Comment by rbarry82** [comment]
No, it doesn't. But "I related two `grafana-agent` charms to the same principal on different subordinates and they're thrashing the same config file" probably equally applies to, like... the entire category of subordinates, honestly.

**Comment by dstathis** [comment]
We have no way to stop. It will obviously break if you do it. As Ryan said, that is probably true of every subordinate ever.

**Comment by sed-i** [comment]
Do you think we should recommend `limit: 1` for `cos-agent` provider (kafka, zk, ...)?
cc @Abuelodelanada

**Comment by rbarry82** [comment]
I guess the question is, somewhat "what are the odds?" 

It wouldn't hurt to sneak it into a PR, but it's probably low priority enough not to deserve an issue on its own IMO

**Comment by Abuelodelanada** [comment]
> Do you think we should recommend `limit: 1` for `cos-agent` provider (kafka, zk, ...)?
> cc @Abuelodelanada 

My gut feeling is that there is no point in having more than one.
