### ISSUE TITLE
It is no longer possible to share single files over a snap plug

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-agent-k8s-operator#146]
https://github.com/canonical/grafana-agent-k8s-operator/blob/1e1363bb604d975076ff272839a2d027b385dc1b/src/machine_charm.py#L426

If a single file is shared, it will be placed immediately in `shared-logs`. Currently, this file will never be picked up by promtail due to how we're globbing.

**Comment by rbarry82** [comment]
@simskij Was this actually tested? Do you have a snippet for a snapcraft.yaml? Because they use [doublestar](https://github.com/bmatcuk/doublestar), and:

```bash
mkdir -p /tmp/shared-logs/test/
touch /tmp/shared-logs/foo
touch /tmp/shared-logs/test/bar
```

Followed by:

```go
package main

import (
        "fmt"
        "github.com/bmatcuk/doublestar/v4"
        "github.com/davecgh/go-spew/spew"
        "os"
)

func main() {
        files, err := doublestar.Glob(os.DirFS("/tmp/shared-logs"), "**/*")
        if err != nil {
                fmt.Printf("ERROR: %+v", err)
        }
        spew.Dump(files)
}
```

Does show:

```
([]string) (len=3 cap=4) {
 (string) (len=3) "foo",
 (string) (len=4) "test",
 (string) (len=8) "test/bar"
}
```

Which will pick up a file at the actual root dir. I don't have a snap build to test this with, but the glob is not excluding the basedir.
