### ISSUE TITLE
Machine charm does not currently traverse log directories

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-agent-k8s-operator#163]
### Bug Description

If a snap slot provides one or multiple nested folders for logs, we currently do not properly recurse these directories to find files. See the attached screenshot

![image](https://user-images.githubusercontent.com/1596025/229156938-4fac98fa-020f-4ae4-b113-401ec813a80a.png)

### To Reproduce

1. `juju deploy zookeeper`, built from source
2. `juju deploy grafana-agent`, built from source
3. `juju relate grafana-agent zookeeper`
4. relate via CMRs to Grafana

### Environment

- 

### Relevant log output

```shell
2023-03-31 16:56:57	
Mar 31 14:56:56 juju-8c976f-6 grafana-agent.grafana-agent[10431]: ts=2023-03-31T14:56:56.954835365Z caller=filetarget.go:317 level=info component=logs logs_config=log_file_scraper msg="failed to tail file" error="file is a directory" filename=/snap/grafana-agent/11/shared-logs/zookeeper/version-2
2023-03-31 16:56:56	
ts=2023-03-31T14:56:56.954835365Z caller=filetarget.go:317 level=info component=logs logs_config=log_file_scraper msg="failed to tail file" error="file is a directory" filename=/snap/grafana-agent/11/shared-logs/zookeeper/version-2
```

**Comment by lucabello** [comment]
Turns out that the `__path__` configuration accepts a glob which is parsed using this [bmatcuk/doublestar](https://github.com/bmatcuk/doublestar) library.

The issue with this is that it doesn't have a way to match files only, so a couple of possible behaviors are:
1. `__path__: .../zookeeper/**` gets all files AND directories, which doesn't get rid of the "file is a directory" error, but it will at least also scrape all the files inside it
2. `__path__: .../zookeeper/**/*.log` get all files with a certain extension, getting rid of the error but limiting ourselves to some file extension for logs in that folder tree

A different solution would be to create a job for each file and pointing the `__path__` to each; having one for each folder would be equivalent to **1** if a folder contains both log files and folders.

**Comment by simskij** [comment]
> Turns out that the `__path__` configuration accepts a glob which is parsed using this [bmatcuk/doublestar](https://github.com/bmatcuk/doublestar) library.
> 
> The issue with this is that it doesn't have a way to match files only, so a couple of possible behaviors are:
> 
> 1. `__path__: .../zookeeper/**` gets all files AND directories, which doesn't get rid of the "file is a directory" error, but it will at least also scrape all the files inside it
> 2. `__path__: .../zookeeper/**/*.log` get all files with a certain extension, getting rid of the error but limiting ourselves to some file extension for logs in that folder tree
> 
> A different solution would be to create a job for each file and pointing the `__path__` to each; having one for each folder would be equivalent to **1** if a folder contains both log files and folders.

How about we resolve the list of items in the charm, before passing it to promtail/gagent, and filter out the entries that are directories using `os.path.isdir()`?

**Comment by simskij** [comment]
Another option would be to [drop](https://grafana.com/docs/loki/latest/clients/promtail/stages/drop/) the "Failed to tail file ... file is a directory" log lines.
