### ISSUE TITLE
pydantic 2.0 dependency

### ISSUE THREAD

**Issue by jneo8** [canonical/grafana-agent-k8s-operator#214]
### Bug Description

The pydantic just [released 2.0](https://github.com/pydantic/pydantic/releases/tag/v2.0).
So the charm build and and the `PY_DEPS` in library is broken.
Also maybe some fixs are requried for pydantic related code.

### To Reproduce

```
tox -e render-machine
charmcraft pack
```

### Environment

ubuntu 20.04

### Relevant log output

```shell
...
```

### Temporary workaround

Pin pydantic version < 2.0 in `PY_DEPS`

```python
# PYDEPS = ["cosl", "pydantic"]
PYDEPS = ["cosl", "pydantic < 2.0"]
```

**Comment by PietroPasotti** [comment]
just had the same issue in tempo, had to pin it to "<2.0" and it worked for now

**Comment by dragomirp** [comment]
Hi, at the moment clean builds of charms using `lib/charms/grafana_agent/v0/cos_agent.py` would try to pull pydantic 2.0 and fail to pack at least on focal. This happens because charmcraft is updating dependencies based on what is specified in the PYDEPS of charm libs. There's a bug https://github.com/canonical/charmcraft/issues/1135 open for it, but short term charm libs should most probably pin the major version in PYDEPS.

**Comment by erik78se** [comment]
If this is still relevant today, perhaps a notice about the requirements.txt be set to pydantic < 2 to avoid this when using the lib until this requirement has been removed?
